baseURL                   = "https://shenxia.me"
builddrafts                = false
languageCode               = "zn-Hans"
canonifyurls               = true
contentdir                 = "content"
layoutdir                  = "layouts"
publishdir                 = "public"
enableEmoji                = true
hasCJKLanguage             = true
summaryLength              = 200
#Page inate                 = 3

theme                      = "AllinOne"
title                      = "Xia Shen"

pygmentsuseclasses         = true


[permalinks]
  blog                     = "blog/:year-:month/:slug/"
  Moment                   = "Moment/:year-:month/:slug/"
  About                    = "About/:year-:month/:slug/"


[taxonomies]
  tag                      = "tags"
  series                   = "series"
  category                 = "categories"


[menu]
  [[menu.main]]
    name                   = "Blog"
    weight                 = -120
    identifier             = "blog"
    url                    = "blog/"  

  [[menu.main]]
    name                   = "Moment"
    weight                 = -110
    identifier             = "moment"
    url                    = "moment/" 

  [[menu.main]]
    name                   = "About Me"
    weight                 = -100
    identifier             = "about"
    url                    = "about/"  

 

[params]
  faviconfile              = "img/shen.jpg"               # from static/
  avatar                   = "img/profile.jpg"             # path to image in static dir e.g img/avatar.png 
  author                   = "Xia Shen"
  description              = ["Be myself.", "Love the wonderful world.", "流光容易把人抛 红了樱桃 绿了芭蕉"]           # appears in the site header when set to a non-empty string
  welcome_head             = "Hello, World!"
  welcome_word             = "The greatest test of courage on earth is to bear defeat without losing confidence."

  latestpostscount         = 5                             # how many posts to display on the home page
  bloggroupby              = 'month'
  dateform                 = "Jan 2, 2006"
  dateformfull             = "2006-01-02  Monday  15:04:05"
  noshowreadtime           = false                         # if true, don't show "<x> minutes read" in posts

  # slides
 slidesDirPath             = "themes/AllinOne/static/img/header-slides"  
 slidesDirPathURL          = "img/header-slides"


  # highlighting 
  highlightjs              = true 

  # latex
  katex                    = true

  # links
  email                    = "qq951633542@163.com"
  github                   = "https://github.com/shineshen007"
  include_rss              = true                          # include RSS <link> tag in <head> and show RSS icon
  
  # analytics
  googleAnalytics          = "your-google-analytic-id"
    