---
title: Somewhere the sun is shining
author: By Jessica M. Raymond
date: '2019-08-13'
slug: moment
categories: []
tags: ["life"]
---
Somewhere the sun is shining,

and the clouds are not in sight,

某处阳光正好，

天空看不见白云飘摇。

Somewhere some's laughing,

and talking about what might.

某处有人在笑，

谈论着今后的生活。

What might have been another year,

for us to spend together.

来年会是什么样子，

让我们一起度过。

What might have been another time,

that I could cherish forever.

下次会是什麽样子，

让我能永远珍惜。

Somewhere two people laugh and joke,

and carry on all day.

某处两人正在谈笑，

一整天笑弯了腰。

Talk about their past and future,

In an extraordinary way.

谈论他们的过去和未来，

是多么非凡精彩。

They talk about the last few years,

And how they made a bond.

他们谈论刚过去的岁月，

他们是如何密不可分。

They found it funny they both were different,

But both especially fond.

他们发现彼此不同多么有趣，

却又格外相亲相爱。

Fond of each other every day,

So genuine and true.

每一天都深爱对方，

如此真实可信。

A friend to tell of all your worries,

If ever you are blue.

一个能够分担一切忧伤的朋友，

无论你何时感到忧伤。

To trust with all my secrets,

And keeping yours close to heart.

能够付托我所有的秘密，

也会将你的秘密深藏心底。

Knowing you will comfort me,

And we will meet again.

知道你会安慰我，

也会分享我们所有的成绩。

Somewhere the sun is shining,

And we will meet again.

某处阳光正好，

我们会再次相遇。

Become the friends we always were,

And talk about what's been.

我们会成为永远的朋友，

也谈论过去的经历。

Although you're gone I know you're here,

To help me through hard times.

虽然你已离去，我知道你仍在这里，

帮助我度过艰难时期。

Help me make the right decisions,

When I don't see the signs.

帮助我做出正确的决定，

当我需要方向的指引。

Somewhere the sun is shining,

And you will be in my heart.

某处阳光正好，

而你会在我心里。

For you were more like a sister to me,

And shall never part.

因为你就是我的姐妹，

我们永不分离。

This is the time to let you know,

how much I ready cared.

现在是时候让你知道，

我有多么在乎你。

I love you

For you no matter what,

And cherish the moments that we shared.

无论经历何事，我一直都深爱你，

并珍惜我们共度的所有时光。
