---
title: Someone like you
author: ''
date: '2020-03-24'
slug: some-on-like
categories:
  - life
tags:
  - life
---
I heard, that your settled down.

已闻君，诸事安康。

That you, found a girl and yourmarried now.

遇佳人，不久婚嫁。

I heard that your dreams came true.

已闻君，得偿所想。

Guess she gave you things, I didn't give to you.

料得是，卿识君望。

Old friend, why are you so shy?

旧日知己，何故张皇？

It ain't like you to hold back orhide from the lie.

遮遮掩掩，欲盖弥彰。

I hate to turn up out of the blue uninvited.

客有不速，实非我所想。

But I couldn't stay away, I couldn't fight it.

避之不得，遑论与相抗。

I'd hoped you'd see my face& that you'd be reminded,

异日偶遇，识得依稀颜。

That for me, it isn't over.

再无所求，涕零而泪下。

Never mind, I'll find someone like you.

毋须烦恼，终有弱水替沧海。

I wish nothing but the best, for you too.

抛却纠缠，再把相思寄巫山。

Don't forget me, I beg, I remember yousaid:

勿忘昨日，亦存君言于肺腑。

"Sometimes it lasts in love but sometimes it hurts instead"

情堪隽永，也善心潮掀狂澜。

You'd know, how the timeflies.

光阴常无踪，词穷不敢道荏苒。

Only yesterday, was the time of our lives.

欢笑仍如昨，今却孤影忆花繁。

We were born and raised in a summer haze.

彼时初执手，夏雾郁郁湿衣衫。

Bound by the surprise of our glory days.

自缚旧念中，诧喜荣光永不黯。

I hate to turn up out of the blue uninvited.

客有不速，实非我所想。

But I couldn't stay away, I couldn't fight it.

避之不得，遑论与相抗。

I'd hoped you'd see my face& that you'd be reminded,

异日偶遇，识得依稀颜。

That for me, it isn'tover.

再无所求，涕零而泪下。

Never mind, I'll find someone like you.

毋须烦恼，终有弱水替沧海。

I wish nothing but the best, for you too.

抛却纠缠，再把相思寄巫山。

Don't forget me, I beg, I remember yousaid:

勿忘昨日，亦存君言于肺腑。

Sometimes it lasts in love but sometimes it hurts instead, yeah.

情堪隽永，也善心潮掀狂澜。

Nothing compares, no worries orcares.

无可与之相提，切莫忧心同挂念。

Regret's and mistakes they're memories made.

糊涂遗恨难免，白璧微瑕方可恋。

Who would have known how bitter sweet this would taste?

此中酸甜苦咸，世上谁人堪相言？

Nevermind, I'll find someone like you.

毋须烦恼，终有弱水替沧海。

I wish nothing but the best, for you too.

抛却纠缠，再把相思寄巫山。

Don't forget me, I beg, I remember yousaid:

勿忘昨日，亦存君言于肺腑。

Sometimes it lasts in love but sometimes it hurts instead, yeah.

情堪隽永，也善心潮掀狂澜。

Nevermind, I'll find someone likeyou.

毋须烦恼，终有弱水替沧海。

I wish nothing but the best, for you too.

抛却纠缠，再把相思寄巫山。

Don't forget me, I beg, I remember yousaid:

勿忘昨日，亦存君言于肺腑。

Sometimes it lasts in love but sometimes it hurts instead, yeah.

情堪隽永，也善心潮掀狂澜。





-----转载于网上，侵删。


