---
title: "ubuntu安装及配置"
author: "shine"
date: '2020-02-21'
slug: ubuntu
tags: []
categories: ubuntu
---

  2017年开始接触Linux，选择了ubuntu练手，轮番折腾之后总结出：AMD显卡千万不要装ubuntu，因为驱动不支持。

  装系统很简单，在windows系统下下载UItralSO软件制作启动优盘，制作完成后即可优盘安装ubuntu，不同电脑优盘启动快捷键不一样，有的还需要BOSS设置一下优先U盘启动。装虚拟机常用virtualbox和VMWARE两款软件。

  安装成功后接着修改软件源，美化主题,安装tweaktools，还可以安装docky和系统监视导航。

  然后就是设置root，sudo passwd root root，安装chorme和搜狗输入法，输入法安装完成之后需要设置一下，设置-文本输入-勾掉显示当前输入法-添加-sogou，安装Java，安装cytoscape,有时候点击下载cytoscape无法下载文件，而是打开源码网页，此时可以在终端，wget http://chianti.ucsd.edu/cytoscape-3.6.1/Cytoscape_3_6_1_unix.sh，下载安装。

有需要的话还可以安装Windows10虚拟机，并实现文件共享。安装WPS，并解决字体缺失问题。

在root模式下安装R和RStudio，可用代码安装R和RStudio，也可下载软件包到本地，直接代码安装的R一般不是最新版本，需要更新。处理一些数据需要配置hdf5和netcdf4，netcdf4可以代码安装，hdf5需要下载下来编译安装。开发R包需要配置git以便于版本控制,RStudio中配置git。以下是Ubuntu中安装某些R包的方法，有些包在终端安装比较方便。设置R镜像.配置xcms包之前需要设置好Bioconductor和CRAN 的镜像，用chooseCRANmirror()和chooseBioCmirror()函数。

Ubuntu安装rgl，rgl

sudo add-apt-repository ppa:marutter/rrutter

sudo apt-get update

sudo apt-get install r-cran-rgl

Ubuntu安装devtools

sudo apt-get install build-essential libcurl4-gnutls-dev libxml2-dev libssl-dev

sudo -i R

install.packages('devtools')

如果出现bioconductor连接不上以及R包装不上的情况，可能是没有启用管理员权限。

把R包push到github，

ssh-keygen -t rsa -C xxxxx@gmail.com（注册github时的email）

一路回车，生成ket plot

找到生成的id_rsa.pub文件，将其中内容拷贝到你的github中，新建SSH KEY，

测试是否链接到github，ssh -T git@github.com

提交代码到github

git init //初始化本地仓库

git commit -m "注释"//提交到要地仓库，并写一些注释

git remote add origin git@github.com:youname/Test.git //连接远程仓库并建了一个名叫：origin的别名

git push -u origin master //将本地仓库的东西提交到地址是origin的地址，master分支下
